[features]
resolution = true
skip-lint = false

[programs.localnet]
flash_book = "5VqBguVaSj8PH6BTk9X5s3nJCHRqAkZfB7G7Bjenzcq"

[programs.devnet]
flash_book = "5VqBguVaSj8PH6BTk9X5s3nJCHRqAkZfB7G7Bjenzcq"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p flash-book"

[workspace]
members = [
    "programs/flash-book",
]
