[features]
resolution = true
skip-lint = false

[programs.localnet]
flash_book = "Di8ZzxmMb5Ho2xWHbvcAxKPjcaVXTCM7U5xe5Gm7uLVF"

[programs.devnet]
flash_book = "Di8ZzxmMb5Ho2xWHbvcAxKPjcaVXTCM7U5xe5Gm7uLVF"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun test programs/flash-book/tests"

[workspace]
members = [
    "programs/flash-book",
]
